name: campus_utility_app
description: "A University Campus Utility Flutter App - Semester Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for REST APIs communication
  http: ^1.2.1

  # State Management provider
  provider: ^6.1.2

  # Local Key-Value Storage for JWT Auth Token and offline session cache
  shared_preferences: ^2.2.3

  # Image Picker for camera/gallery photo select in Marketplace uploads
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
